### ISSUE TITLE
Enhance the design of the Header and Footer

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/fork-commit-merge-web#111]
Enhance the design of the header `components/layout/Header.tsx` and footer `components/layout/Footer.tsx` to look more modern. This can be anything between new color scheme to hover effects etc.

Feel free to ask here any questions you may have regarding this issue.

**Comment by ivanosquis10** [comment]
Hi Niko, hope you're well. I will try to improve what you ask in the issue and then I will show it to you to see what you think :)

**Comment by nikohoffren** [comment]
> Hi Niko, hope you're well. I will try to improve what you ask in the issue and then I will show it to you to see what you think :)

Sure, go ahead!

**Comment by ivanosquis10** [comment]
Hey Niko, how're you doing? I've been sick, but I'll show you what I've got so far

![image](https://github.com/nikohoffren/fork-commit-merge-web/assets/83567373/f1980710-b03b-406e-8b4d-2edaf5c56b82)
![image](https://github.com/nikohoffren/fork-commit-merge-web/assets/83567373/2df8ea52-4316-49d8-86bf-1b59058ef1df)
![image](https://github.com/nikohoffren/fork-commit-merge-web/assets/83567373/6ab0daf6-fbde-48e1-953c-26ee73e4bfa8)

**Comment by nikohoffren** [comment]
> Hey Niko, how're you doing? I've been sick, but I'll show you what I've got so far
> 
> ![image](https://user-images.githubusercontent.com/83567373/272118754-f1980710-b03b-406e-8b4d-2edaf5c56b82.png) ![image](https://user-images.githubusercontent.com/83567373/272118792-2df8ea52-4316-49d8-86bf-1b59058ef1df.png) ![image](https://user-images.githubusercontent.com/83567373/272118872-6ab0daf6-fbde-48e1-953c-26ee73e4bfa8.png)

I like that a lot, looks much modern than the current design on the site. Are there any hover effects on the links or just the underline that was before? I'm already happy with those changes.
