### ISSUE TITLE
More language components needed

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/fork-commit-merge-web#137]
In the website, there are is Language dropdown menu in the header/navbar.
Add more languages that are not yet in this list. The Language components has to be made similarly as the other components, so you can simply copypaste existing language component inside `components/languageComponents` directory and create new component from that by adding the information needed as well as the badge image if it is available. 

After creating the component:
-   Add the path to `data/languageList.ts` file similarly as the other paths.
-   Add the component inside `pages/languages/[lang].tsx` file same way as the other components are added.

Remember to ask permission to get signed for this task to avoid other contributors possible working at the same issue and avoiding conflicts.

Feel free to ask any questions here if you have some problems!

**Comment by arbiasgjoshi** [comment]
Hi @nikohoffren, 

I'd like to be assigned to this issue. In the meantime, I will be working on the issue attempting to finish and make PR as soon as you will approve my request, if that is fine with you? 

If any questions might come, I will reply to this thread.

**Comment by nikohoffren** [comment]
> Hi @nikohoffren,
> 
> I'd like to be assigned to this issue. In the meantime, I will be working on the issue attempting to finish and make PR as soon as you will approve my request, if that is fine with you?
> 
> If any questions might come, I will reply to this thread.

Sure!

In this project i have also ESLint set up in a way that in paragraphs or other text, every `'` character has to be escaped with `&apos;` and every `"` character has to be escaped with `&quot`. For example like this in the Dart language component:
```javascript
<p className="mb-4">
    Dart is an object-oriented, class-based programming language developed
    by Google. Initially released in 2011, it is designed for ease of use,
    strong support for modern web workflows, and robustness. Dart is used
    for building web, server, and mobile applications, and is also the
    language behind Flutter, Google&apos;s UI toolkit for building
    natively compiled applications for mobile, web, and desktop.
</p>
```
There the `Google's` is written like `Google&apos;s` to avoid any errors.

**Comment by arbiasgjoshi** [comment]
Thanks for the additional info. Will be using that and come back with a commit in a shortly manner. 

Thanks,
