### ISSUE TITLE
More Language components needed

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/fork-commit-merge-web#140]
In the website, there is Languages dropdown menu in the header/navbar.
Add more languages that are not yet in this list. The Language components has to be made similarly as the other components, so you can simply copypaste existing language component inside `components/languageComponents` directory and create new component from that by adding the information needed as well as the badge image if it is available. 

After creating the component:
-   Add the path to `data/languageList.ts` file similarly as the other paths.
-   Add the component inside `pages/languages/[lang].tsx` file same way as the other components are added.

Remember to ask permission to get signed for this task to avoid other contributors possible working at the same issue and avoiding conflicts.

Feel free to ask any questions here if you have some problems!

**Comment by AlexHoop140** [comment]
Hi @nikohoffren,
I want to ask if Delphi is ok?

**Comment by nikohoffren** [comment]
> Hi @nikohoffren, I want to ask if Delphi is ok?

Yeah sure! Any programming language is ok to add. Shall i assign you to this task?

**Comment by AlexHoop140** [comment]
> > Hi @nikohoffren, I want to ask if Delphi is ok?
> 
> Yeah sure! Any programming language is ok to add. Shall i assign this issue to you?

Yes, please.

**Comment by nikohoffren** [comment]
> > > Hi @nikohoffren, I want to ask if Delphi is ok?
> > 
> > 
> > Yeah sure! Any programming language is ok to add. Shall i assign this issue to you?
> 
> Yes, please.

Okay, sounds good! 

I also need to clarify that in this project i have configured ESLint in a way that inside of header tags or paragraphs, every `'` character has to be escaped with `&apos;` and every `"` character has to be escaped using `&quot;`.
Here is an example:
```jsx
<p className="mb-6">
          Clojure offers several advantages such as high performance via JVM,
          simplicity with its small set of powerful language constructs, and
          strong support for concurrent programming. It&apos;s also highly
          extensible and has a robust ecosystem, making it a solid choice for a
          variety of software projects, including web services and data
          analytics applications.
</p>
```
There you can see that the `'` has replaced with `&apos;`, otherwise the build in Vercel will fail.
