### ISSUE TITLE
Enhance the footer design 

### ISSUE THREAD

**Issue by anshulsoni4** [nikohoffren/fork-commit-merge-web#29]
i want to edit the footer, as it is very small and not user friendly
will make it more attractive

**Comment by nikohoffren** [comment]
> i want to edit the footer, as it is very small and not user friendly
> will make it more attractive 

Sounds good! Just make a pull request when you are done.

**Comment by anshulsoni4** [comment]
> > i want to edit the footer, as it is very small and not user friendly
> > will make it more attractive
> 
> Sounds good! Just make a pull request when you are done.

thanks man

**Comment by nikohoffren** [comment]
> i want to edit the footer, as it is very small and not user friendly will make it more attractive

Hi, are you still working on this issue?
