### ISSUE TITLE
Add more Language/Library/Framework descriptions

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/fork-commit-merge-web#40]
Add more Language/Library/Framework descriptions to `components/Descriptions.tsx` file about technologies used in [Fork, Commit, Merge repository](https://github.com/nikohoffren/fork-commit-merge).

**Comment by ATREAY** [comment]
Hello @nikohoffren,

I have filed a pull request associated with this particular issue.
Kindly review it. 

Thank you!
