### ISSUE TITLE
No favicon in the project

### ISSUE THREAD

**Issue by ivanosquis10** [nikohoffren/fork-commit-merge-web#92]
It doesn't have a "fav icon", it would be cool if it did. If it is in your plans:)

**Comment by nikohoffren** [comment]
> It doesn't have a "fav icon", it would be cool if it did. If it is in your plans:)

Good call! Favicons should definitely be added at some point. Feel free to make a pull request out of this with some dummy source paths if you are interested, i will add the actual icons later on. Or we can also wait someone else to tackle this issue.

**Comment by ivanosquis10** [comment]
Great, I converted the project icon to svg to make it work and then if you change it, the reference remains :)
